name: Build and Test mdpreview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      
      - name: Install dependencies
        working-directory: ./mdpreview/src/
        run: |
          go mod tidy
          go mod vendor
          go install github.com/becheran/go-testreport@latest

      - name: Test
        working-directory: ./mdpreview/src/
        run: go test -v -coverprofile=coverage.out -covermode=atomic -json ./... | go-testreport $GITHUB_STEP_SUMMARY
      
      - name: Build
        working-directory: ./mdpreview/src/
        run: go build -C ./mdpreview/src/ -o bin/mdpreview && rm -rf bin/mdpreview
      
      
